In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []

In [4]:
for i in range(0,len(a)):
    ab.append(a[i]*b[i])

In [5]:
ab

[2, 6, 12, 20]

In [6]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [7]:
a*b

array([ 2,  6, 12, 20])

Array Oluşturma

In [8]:
import numpy as np

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.random.randint(0,10,size=10)

array([2, 4, 8, 1, 6, 0, 8, 5, 9, 9])

In [14]:
np.random.normal(10,4,(3,4))#ortalaması 10, standart sapması 4 olan 3*4 martix

array([[ 9.73707478, 17.3852949 ,  4.23886319, 15.89748553],
       [15.16362855,  9.55878469,  5.43002073,  6.45813284],
       [ 5.24919998,  9.67304283,  7.58939327,  7.54330619]])

Numpy Array Özellikleri

In [15]:
import numpy as np

In [16]:
a = np.random.randint(10,size=5)

In [17]:
a.ndim #boyut sayısı

1

In [18]:
a.shape #boyut bilgisi

(5,)

In [19]:
a.size #toplam eleman sayısı

5

In [20]:
a.dtype #tipler

dtype('int32')

Reshaping

In [1]:
import numpy as np
np.random.randint(1,10,size=9)

array([1, 3, 5, 3, 5, 5, 3, 6, 8])

In [2]:
np.random.randint(1,10,size=9).reshape(3,3)

array([[9, 6, 2],
       [9, 6, 7],
       [8, 1, 6]])

In [3]:
ar = np.random.randint(1,10,size=9)

In [4]:
ar

array([2, 8, 4, 3, 3, 6, 7, 1, 9])

In [5]:
ar.reshape(3,3)

array([[2, 8, 4],
       [3, 3, 6],
       [7, 1, 9]])

index işlemleri

In [8]:
import numpy as np
a = np.random.randint(1,10,size=9)

In [9]:
a[0]

2

In [10]:
a[0:5]

array([2, 4, 3, 2, 8])

In [12]:
a[0] = 999

In [13]:
m = np.random.randint(10,size=(3,5))

In [14]:
m

array([[2, 4, 7, 4, 0],
       [6, 0, 7, 9, 6],
       [9, 5, 4, 9, 0]])

In [15]:
m[0,0]

2

In [16]:
m[1,1]

0

In [17]:
m[1,3]

9

In [18]:
m[1,3] = 999

In [19]:
m

array([[  2,   4,   7,   4,   0],
       [  6,   0,   7, 999,   6],
       [  9,   5,   4,   9,   0]])

In [20]:
m[0,0] = 2.3

In [21]:
m

array([[  2,   4,   7,   4,   0],
       [  6,   0,   7, 999,   6],
       [  9,   5,   4,   9,   0]])

In [22]:
m[:0]

array([], shape=(0, 5), dtype=int32)

In [23]:
m[1,:]

array([  6,   0,   7, 999,   6])

In [24]:
m[0:2,0:3]

array([[2, 4, 7],
       [6, 0, 7]])

fancy index

In [25]:
import numpy as np

In [31]:
v = np.arange(0,30,3) #0'dan 30'a kadar(hariç) 3 artarak bir array oluştur.

In [32]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [33]:
v[1]

3

In [34]:
v[4]

12

In [35]:
catch = [1,2,3]

In [36]:
v[catch]

array([3, 6, 9])

Koşullu İşlemler

In [37]:
import numpy as np
v = np.array([1,2,3,4,5])

In [38]:
#klasik döngü

In [39]:
ab = []

for i in v:
    if i<3:
        ab.append(i)

In [40]:
ab

[1, 2]

In [41]:
#numpy ile
v<3

array([ True,  True, False, False, False])

In [42]:
v[v<3] # <, >, !=, ==, >=

array([1, 2])

In [43]:
v

array([1, 2, 3, 4, 5])

Matematiksal İşlemler

In [44]:
import numpy as np
v = np.array([1,2,3,4,5])

In [45]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [46]:
v*5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [47]:
v**2

array([ 1,  4,  9, 16, 25])

In [48]:
v-1

array([0, 1, 2, 3, 4])

In [49]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [50]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [51]:
np.mean(v)

3.0

In [52]:
np.sum(v)

15

In [53]:
np.min(v)

1

In [55]:
np.max(v)

5

In [56]:
np.var(v)

2.0

In [57]:
v = np.subtract(v,1)

İki bilinmeyenli bir problem çözümü

In [58]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [59]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [60]:
import numpy as np
np.fives(10)

AttributeError: module 'numpy' has no attribute 'fives'

In [61]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('1. boyuttaki 2.eleman: ', arr[0, 1])

1. boyuttaki 2.eleman:  2


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [63]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7])

filter_array = array % 2 == 0

new_array = array[filter_array]

print(new_array)

[2 4 6]
